### ISSUE TITLE
CONCURRENCY_LIMIT leak detected

### ISSUE THREAD

**Issue by ashleahhill** [jsdf/browserify-cache-api#2]
When will the next patch be released? 

I see that this issue: 

https://github.com/jsdf/browserify-cache-api/blob/f9d06fbfb1ac0faf1e820568e5dcdf538bfd9241/index.js#L11

Is resolved in master, but not in the 1.5.0 version currently released.

**Comment by jsdf** [comment]
Published 1.5.1 as a stopgap, new major version coming soonish

**Comment by ashleahhill** [comment]
This is great! Thanks.
