### ISSUE TITLE
Package cache dead code?

### ISSUE THREAD

**Issue by Macil** [jsdf/browserify-cache-api#6]
I've been getting ready to fix some more bugs with browserify-cache-api, but I figured I should understand all of the existing code first and make unit tests for it before I changed too much so that way I wouldn't break anything without realizing it. I can't figure out what the invalidateFilesPackagePaths and invalidatePackageCache functions are for.

invalidateFilesPackagePaths removes things from `cache.filesPackagePaths`, but nothing else ever reads or writes to that object, so it's always empty. Same with invalidatePackageCache and `cache.packages`.
Additionally, prior to 37f700b5130caf58c095953f2e9f62f2e9af7511, packagePathForPackageFile had a mistake in it so that it would always trigger an exception. I couldn't get the exception to trigger while using browserify-cache-api, and no one has reported it that I've seen, so it seems like the code has been completely dead for a while.

I assume it's incomplete code. Is it for invalidating the cache of files when their package.json files are changed? (I've made a [failing test to track that issue here in a branch](https://github.com/AgentME/browserify-cache-api/commits/fixpackage).) I can fix it up if that's the purpose of it; I just want to make sure there isn't some other purpose that I might unknowingly break in the process.

Is there a point to `BrowserifyCache.getPackageCache`? I'm convinced that it currently always returns an empty object. I'm not sure what type of object it's intended to return, or what it would be used for. BrowserifyIncremental doesn't use it. Any complaints if a future pull request of mine happens to drop that function?

**Comment by jsdf** [comment]
At one point the package data was used by [browserify-assets](https://github.com/jsdf/browserify-assets) (kinda gross because it's using data from a cache for non-caching-related purposes) but I haven't worked on that project for a long time, and don't intend to. I probably should have removed that code already.

Also if you're interested I'm happy to add you as a contributor on Github and npm.

**Comment by Macil** [comment]
Thanks, that explains some things. I'll be more aggressive with cleaning up that code then. I'll mark this closed since that's answered.

I'd be happy with being added on here. I've been interested in browserify-incremental and I believe I've got a good understanding of some of its bugs by now.

**Comment by jsdf** [comment]
I went ahead and removed that dead code: https://github.com/jsdf/browserify-cache-api/commit/50d887f2190a785d4f6b9ffe827b243a7daed55b
